version: "3"
services:
  springboot-app:
    image: springboot-emedlogix
    restart: always
    build: .
    ports:
      - 9000:8080
    environment:
     MYSQL_HOST: mysqldb
     MYSQL_USER: root
     MYSQL_PASSWORD: jerald123
     MYSQL_PORT: 3307
