version: "3"
services:
  springboot-app:
    image: springboot-emedlogix
    restart: always
    build: .
    ports:
      - 9000:8080
    environment:
     MYSQL_HOST: mysqldb
     MYSQL_USER: root
     MYSQL_PASSWORD: jerald123
     MYSQL_PORT: 3307
  mysqldb:
      container_name: mysqldb
      image: mysql
      volumes:
        -  /home/user/Desktop/db:/var/lib/mysql
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: emedlogix
        MYSQL_ROOT_PASSWORD: jerald123
